-- BadgeForge Supabase schema — PRD-aligned
-- Run in Supabase SQL editor or via migration

-- Users (extend if using Supabase Auth)
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Seed items (GMAsia + curated content)
CREATE TABLE IF NOT EXISTS items (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('article', 'video', 'practice', 'other')),
  description TEXT,
  date DATE,
  embedding JSONB, -- Optional: array of numbers for similarity (enable pgvector for native)
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Items with precomputed embeddings (ai/ produces this)
CREATE TABLE IF NOT EXISTS items_with_embeddings (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  type TEXT NOT NULL,
  description TEXT,
  date DATE,
  embedding JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Learning paths (generated by /api/generate_path)
CREATE TABLE IF NOT EXISTS paths (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id),
  goal TEXT NOT NULL,
  path_json JSONB NOT NULL,
  rationale TEXT,
  use_canned BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Issued badges
CREATE TABLE IF NOT EXISTS badges (
  id TEXT PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  user_email TEXT,
  goal TEXT NOT NULL,
  path_summary TEXT NOT NULL,
  signature TEXT NOT NULL,
  l2_anchor_tx TEXT,
  issued_at TIMESTAMPTZ DEFAULT now()
);

-- Notifs / event log (for demo panel)
CREATE TABLE IF NOT EXISTS notifs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type TEXT NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS (optional)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE items ENABLE ROW LEVEL SECURITY;
ALTER TABLE badges ENABLE ROW LEVEL SECURITY;
